### ISSUE TITLE
La página es recargada

### ISSUE THREAD

**Issue by JavierOrtunoRoig** [lintenn/SwishGames#2]
La página es recargada en vez de usar react-router-dom para cambiar un componente por otro.

Pasa al clickar en los siguientes botones:
![image](https://user-images.githubusercontent.com/54411055/162563713-0b98edf8-0313-4e4a-8b84-08439bdc51e1.png)

**Comment by AngelJRM01** [comment]
Thanks for finding that problem, I've already fixed it.
