### ISSUE TITLE
Pantalla vacía al buscar juegos que no existen

### ISSUE THREAD

**Issue by JavierOrtunoRoig** [lintenn/SwishGames#3]
Si buscas un juego que no existe la pantalla se queda vacía, no da ninguna info de que no hay juego (poco usable).
El footer no se queda abajo y se sube a arriba

![image](https://user-images.githubusercontent.com/54411055/162563732-1db864d3-335d-427b-af10-0215ef359c7a.png)

**Comment by AngelJRM01** [comment]
Thanks for finding that problem, I've already fixed it
